# apiVersion: V1
# kind: Secret
# metadata:
#   name: mongodb-secret
# type: Opaque
# data:
#   mongo-username: Y2hhaXRhbnlh
#   mongo-password: Y2hhaXRhbnlhIzEyMzQ=
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  mongo-username: Y2hhaXRhbnlh
  mongo-password: Y2hhaXRhbnlhIzEyMzQ=
